name: Deploy to Server via FTP

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Deploy via FTP (demos)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.ajdrafts.com
          username: github@ajdrafts.com
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /demos/activity-log-v2/

      - name: Deploy via FTP (projects)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.ajdrafts.com
          username: github@ajdrafts.com
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /projects/activity-log-v2/
